version: '3'

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com.br"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "15432:80"
    depends_on:
      - postgresdb
    networks:
      - postgres-network

  server:
    build: .
    environment:
      SQL_HOST: "postgresdb" 
      SQL_PORT: 5432 
      SQL_USER: "postgres" 
      SQL_PASSWORD: "admin" 
      SQL_DBNAME: "theater_db" 
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge

volumes:
  data: